-- Property Wanted CRM Route A V7 Migration
-- Safe migration: adds PropertyGuru-style listing fields and richer units/options.
-- Run this after migration_v6_units.sql. It does not delete existing data.

alter table public.owner_properties
  add column if not exists property_sub_type text,
  add column if not exists property_unit_type text,
  add column if not exists available_mode text default 'Immediately',
  add column if not exists available_date date,
  add column if not exists lease_term text,
  add column if not exists built_up_width numeric default 0,
  add column if not exists built_up_length numeric default 0,
  add column if not exists built_up_dimension_unit text default 'ft',
  add column if not exists land_width numeric default 0,
  add column if not exists land_length numeric default 0,
  add column if not exists land_dimension_unit text default 'ft',
  add column if not exists title_type text default 'Individual',
  add column if not exists lease_year_remaining numeric default 0,
  add column if not exists bumi_lot text default 'Prefer not to say',
  add column if not exists direction text,
  add column if not exists property_facilities text,
  add column if not exists block text,
  add column if not exists floor text,
  add column if not exists unit_house_no text,
  add column if not exists hide_unit_number boolean default true,
  add column if not exists parking_spots integer default 0,
  add column if not exists unit_features text,
  add column if not exists condition text default 'Bare',
  add column if not exists electricity_phase text,
  add column if not exists electricity_supply numeric default 0,
  add column if not exists cargo_lifts integer default 0,
  add column if not exists passenger_lifts integer default 0,
  add column if not exists maximum_lift_capacity numeric default 0;

alter table public.agent_listings
  add column if not exists property_sub_type text,
  add column if not exists property_unit_type text,
  add column if not exists available_mode text default 'Immediately',
  add column if not exists available_date date,
  add column if not exists lease_term text,
  add column if not exists built_up_width numeric default 0,
  add column if not exists built_up_length numeric default 0,
  add column if not exists built_up_dimension_unit text default 'ft',
  add column if not exists land_width numeric default 0,
  add column if not exists land_length numeric default 0,
  add column if not exists land_dimension_unit text default 'ft',
  add column if not exists title_type text default 'Individual',
  add column if not exists lease_year_remaining numeric default 0,
  add column if not exists bumi_lot text default 'Prefer not to say',
  add column if not exists direction text,
  add column if not exists property_facilities text,
  add column if not exists block text,
  add column if not exists floor text,
  add column if not exists unit_house_no text,
  add column if not exists hide_unit_number boolean default true,
  add column if not exists parking_spots integer default 0,
  add column if not exists unit_features text,
  add column if not exists condition text default 'Bare',
  add column if not exists electricity_phase text,
  add column if not exists electricity_supply numeric default 0,
  add column if not exists cargo_lifts integer default 0,
  add column if not exists passenger_lifts integer default 0,
  add column if not exists maximum_lift_capacity numeric default 0;

alter table public.new_project_listings
  add column if not exists property_sub_type text,
  add column if not exists property_unit_type text,
  add column if not exists available_mode text default 'Immediately',
  add column if not exists available_date date,
  add column if not exists lease_term text,
  add column if not exists built_up_width numeric default 0,
  add column if not exists built_up_length numeric default 0,
  add column if not exists built_up_dimension_unit text default 'ft',
  add column if not exists land_width numeric default 0,
  add column if not exists land_length numeric default 0,
  add column if not exists land_dimension_unit text default 'ft',
  add column if not exists title_type text default 'Individual',
  add column if not exists lease_year_remaining numeric default 0,
  add column if not exists bumi_lot text default 'Prefer not to say',
  add column if not exists direction text,
  add column if not exists property_facilities text,
  add column if not exists parking_spots integer default 0,
  add column if not exists unit_features text,
  add column if not exists condition text default 'Bare',
  add column if not exists electricity_phase text,
  add column if not exists electricity_supply numeric default 0,
  add column if not exists cargo_lifts integer default 0,
  add column if not exists passenger_lifts integer default 0,
  add column if not exists maximum_lift_capacity numeric default 0;
